version: "3.8"
services:

  postgres:
    env_file: .env
    image: postgres:14.10-alpine3.19
    container_name: assets-compass-postgres
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/init_scripts:/docker-entrypoint-initdb.d
      - local_db_storage:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: on-failure:2
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      - main

  pgadmin:
    image: dpage/pgadmin4:8.1
    container_name: assets-compass-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "crack_admin_pass"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - local_pgadmin_storage:/var/lib/pgadmin
    ports:
      - "5433:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - main

volumes:
  local_db_storage:
  local_pgadmin_storage:

networks:
  main:
    driver: bridge
